import "@/styles/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NoteApps",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={
          (inter.className,
          "text-black text-xl bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 ...")
        }
      >
        <main className="max-w-2xl m-auto my-8">
          <h1 className="text-white">Note App by Refund</h1>
          {children}
        </main>
      </body>
    </html>
  );
}
